story/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls'))
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('experience/', views.experience, name='experience'),
    path('skill&interest/', views.skill_int, name='skill_int'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact')
]

story4/models.py
from django.db import models

# Create your models here.

story4/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def experience(request):
    return render(request, 'experience.html')

def skill_int(request):
    return render(request, 'skill_int.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

story4/templates/about.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
            </div>

            <div id="about" class="container-fluid"><br>
                <p class="tiga">About me.</p>
                <div id="garis"></div>
                <br>
                <p class="empat">
                    Ferenica is a second year student<br>
                    of Universitas Indonesia majored <br>
                    in Computer Science. She was born <br>
                    in Kendari, a small capital in middle <br>
                    part of Indonesia, she is 19 years old <br>
                    and 5'5” tall. Besides that, she is <br>
                    also fueled by her passion for <br>
                    learning about graphic designs.
                </p>
                <div>
                    <img class="rounded-circle" src="{% static 'images/foto3.jpg' %}" alt="at beach">
                </div>
            </div>
        </body>
    </div>
</html>

story4/templates/contact.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
            </div>

            <div id="contact" class="container-fluid"><br>
                <p class="tiga">Contact me.</p>
                <div id="garis"></div>
                <br>
                <div class="sembilan">
                    <p>Ferenica Dwi Putri<br>STUDENT</p>
                    <br>
                    <p>Phone : <br>0821-8762-6752</p>
                    <br>
                    <p>Email : <br>ferenicha@gmail.com</p>
                </div>
                <div>
                    <img class="plus" src="{% static 'images/plus.png' %}" alt="ikon plus">
                </div>
                
                <div>
                    <a href="https://twitter.com/ferenichaaa">
                        <img class="twit" src="{% static 'images/twit.png' %}" alt="ikon twitter">
                    </a>
                    <a href="https://www.instagram.com/ferenichaaa/">
                        <img class="insta" src="{% static 'images/insta.png' %}" alt="ikon instagram">
                    </a>
                    <a href="https://www.facebook.com/ferenicadwiputri">
                        <img class="fb" src="{% static 'images/fb.png' %}" alt="ikon facebook">
                    </a>
                    <a href="https://www.linkedin.com/in/ferenica-dwi-56b18b194/">
                        <img class="linkedin" src="{% static 'images/linkedin.png' %}" alt="ikon linkedin">
                    </a>
                </div>
                <div>
                    <p class="sepuluh">Follow me</p>
                </div>
                
            </div>
        </body>
    </div>
</html>

story4/templates/experience.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
            </div>

            <div id="experience" class="container-fluid"><br>
                <p class="tiga">Experience</p>
                <div id="garis"></div>
                <br>

                <div class="main-timeline">
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content">
                            <span class="date">2017-2018</span>
                            <p class="title"><b>Kelompok Ilmiah Remaja <br> SMA Negeri 1 Kendari</b></p>
                            <p class="description">
                                Secretary    
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content right">
                            <span class="date">2018-present</span>
                            <p class="title"><b>Gabungan Putra-putri<br>Sulawesi Tenggara (Gapura UI)</b></p>
                            <p class="description">
                                Head of Public Relation, Publication and Design Division
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content">
                            <span class="date">2019-present</span>
                            <p class="title"><b>Forum Ukhuwah dan Kajian Islam<br>Fasilkom UI</b></p>
                            <p class="description">
                                Staff of Community Social Department
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content right">
                            <span class="date">2019-present</span>
                            <p class="title"><b>Dewan Perwakilan Mahasiswa<br>Fasilkom UI</b></p>
                            <p class="description">
                                Staff of Secretary Division
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </div>
</html>

story4/templates/gallery.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
            </div>

            <div id="gallery" class="container-fluid"><br>
                <p class="tiga">Gallery</p>
                <div id="garis"></div>
                <p id="byMe">Taken by me : )</p>
                <br>
                <img src="{% static 'images/1.jpg' %}" class="byMe">
                <img src="{% static 'images/2.jpg' %}" class="byMe">
                <img src="{% static 'images/3.jpg' %}" class="byMe">
                <img src="{% static 'images/4.jpg' %}" class="byMe">
                <img src="{% static 'images/5.jpg' %}" class="byMe">
                <img src="{% static 'images/6.jpg' %}" class="byMe">
            </div>
        </body>
    </div>
</html>

story4/templates/head.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<meta charset="utf-8">
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0' />
<title>myProfile</title>
<link href="https://fonts.googleapis.com/css?family=Boogaloo|Fjalla+One|Grenze|Livvic&display=swap" rel="stylesheet">

story4/templates/home.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
                <br>
                <br>
            </div>

            <div id="home" class="container-fluid"><br>
                <div id="aturHome">
                    <p class="satu">Hello, I'm</p>
                    <p class="dua">Ferenica<br>Dwi Putri</p>
                </div>
                <div id="garisHome"></div>
                <br>
                <img class="kanan" src="{% static 'images/foto1.jpg' %}" alt="in front of tree">
            </div>
        </body>
    </div>

</html>

story4/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'story4:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'story4:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'story4:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'story4:skill_int' %}">Skill & Interest</a>
            <a class="nav-item nav-link" href="{% url 'story4:gallery' %}">Gallery</a>
            <a class="nav-item nav-link" href="{% url 'story4:contact' %}">Contact</a>   
        </div>
    </div>  
</nav>

story4/templates/skill_int.html
{% load static %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body>
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                {% include 'navbar.html' %}
            </div>

            <div id="skill-interest" class="container-fluid"><br>
                <p class="tiga">Skill</p>
                <div id="garis"></div>
                <br>
                <p class="lima">Interest</p>
                <div id="garisInt"></div>
                <br>
                <br>
                <img class="word" src="{% static 'images/word.png' %}" alt="ikon mcs word">
                <br>
                <br>
                <br>
                <img class="cdr" src="{% static 'images/cdr.png' %}" alt="ikon corel">
                <p class="enam"><b>Microsoft Word</b><br>Intermediate</p>
                <p class="tujuh"><b>CorelDRAW</b><br>Intermediate</p>
                <p class="delapan">Photography<br>Graphic Design</p>
            </div>
        </body>
    </div>
</html>